version: '3.4'

services:
  todolist.web.rest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"

  todolist.web.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8082:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  todolist.web.grpcui:
    environment:
      - GRPCUI_PORT=8080
      - GRPCUI_SERVER=todolist.web.grpc:80
    ports:
      - "8083:8080"
